// resources/js/Components/AddExperience.jsx
import React, { useState } from 'react';
import { useForm } from '@inertiajs/react';
import TextInput from '@/Components/TextInput';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import SecondaryButton from '@/Components/SecondaryButton';
import axios from 'axios';

export default function AddExperience() {
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState('');
    const { data, setData, post, processing, errors, reset } = useForm({
        title: '',
        startDate: '',
        endDate: '',
        description: ''
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        post(route('experience.store'), {
            onSuccess: () => {
                reset();
            }
        });
    };

    const handleCorrection = async () => {
        if (!data.description.trim()) return;

        setIsLoading(true);
        setError('');

        try {
            const response = await axios.post(route('experience.correct-description'), {
                description: data.description
            });

            if (response.data.success) {
                setData('description', response.data.description);
            } else {
                setError(response.data.message || 'Une erreur est survenue lors de la correction');
            }
        } catch (error) {
            setError(error.response?.data?.message || 'Une erreur est survenue lors de la correction');
            console.error('Erreur lors de la correction:', error);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
            <form onSubmit={handleSubmit} className="space-y-6">
                <div>
                    <InputLabel htmlFor="title" value="Titre" />
                    <TextInput
                        id="title"
                        type="text"
                        name="title"
                        value={data.title}
                        className="mt-1 block w-full"
                        onChange={e => setData('title', e.target.value)}
                        required
                    />
                    {errors.title && <div className="text-red-500">{errors.title}</div>}
                </div>

                <div>
                    <InputLabel htmlFor="start_date" value="Date de début" />
                    <TextInput
                        id="start_date"
                        type="date"
                        name="start_date"
                        value={data.start_date}
                        className="mt-1 block w-full"
                        onChange={e => setData('start_date', e.target.value)}
                        required
                    />
                    {errors.start_date && <div className="text-red-500">{errors.start_date}</div>}
                </div>

                <div>
                    <InputLabel htmlFor="end_date" value="Date de fin" />
                    <TextInput
                        id="end_date"
                        type="date"
                        name="end_date"
                        value={data.end_date}
                        className="mt-1 block w-full"
                        onChange={e => setData('end_date', e.target.value)}
                        required
                    />
                    {errors.end_date && <div className="text-red-500">{errors.end_date}</div>}
                </div>

                <div>
                    <InputLabel htmlFor="description" value="Description" />
                    <textarea
                        id="description"
                        name="description"
                        value={data.description}
                        onChange={e => setData('description', e.target.value)}
                        required
                        className="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
                        rows="4"
                    />
                    {errors.description && <div className="text-red-500">{errors.description}</div>}
                    {error && <div className="mt-2 text-red-500">{error}</div>}
                </div>

                <div className="flex items-center justify-end space-x-4">
                    <SecondaryButton
                        type="button"
                        onClick={handleCorrection}
                        disabled={isLoading || !data.description.trim()}
                        className="relative"
                    >
                        {isLoading ? (
                            <>
                                <span className="opacity-0">Corriger</span>
                                <div className="absolute inset-0 flex items-center justify-center">
                                    <svg className="animate-spin h-5 w-5 text-gray-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                    </svg>
                                </div>
                            </>
                        ) : (
                            'Corriger'
                        )}
                    </SecondaryButton>
                    <PrimaryButton type="submit" disabled={processing || isLoading}>
                        Valider
                    </PrimaryButton>
                </div>
            </form>
        </div>
    );
}

// resources/js/Components/AddExperience.vue
<template>
  <form @submit.prevent="submit" class="space-y-6">
    <div>
      <InputLabel for="title" value="Titre du poste" />
      <TextInput
        id="title"
        type="text"
        class="mt-1 block w-full"
        v-model="form.title"
        required
        autofocus
      />
      <InputError class="mt-2" :message="form.errors.title" />
    </div>

    <div>
      <InputLabel for="company" value="Entreprise" />
      <TextInput
        id="company"
        type="text"
        class="mt-1 block w-full"
        v-model="form.company"
        required
      />
      <InputError class="mt-2" :message="form.errors.company" />
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <InputLabel for="start_date" value="Date de début" />
        <TextInput
          id="start_date"
          type="date"
          class="mt-1 block w-full"
          v-model="form.start_date"
          required
        />
        <InputError class="mt-2" :message="form.errors.start_date" />
      </div>

      <div>
        <InputLabel for="end_date" value="Date de fin" />
        <TextInput
          id="end_date"
          type="date"
          class="mt-1 block w-full"
          v-model="form.end_date"
        />
        <InputError class="mt-2" :message="form.errors.end_date" />
      </div>
    </div>

    <div>
      <InputLabel for="description" value="Description" />
      <textarea
        id="description"
        class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
        v-model="form.description"
        rows="4"
        required
      ></textarea>
      <InputError class="mt-2" :message="form.errors.description" />
      <div class="mt-2">
        <button
          type="button"
          @click="handleCorrection"
          :disabled="isLoading || !form.description.trim()"
          class="inline-flex items-center px-4 py-2 bg-[#2b8d96] border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-[#1a526a] focus:bg-[#1a526a] active:bg-[#1a526a] focus:outline-none focus:ring-2 focus:ring-[#2b8d96] focus:ring-offset-2 transition ease-in-out duration-150 disabled:opacity-50"
        >
          {{ isLoading ? 'Correction en cours...' : 'Corriger avec GEO-AI' }}
        </button>
        <p v-if="error" class="mt-2 text-sm text-red-600">{{ error }}</p>
      </div>
    </div>

    <div>
      <InputLabel for="location" value="Lieu" />
      <TextInput
        id="location"
        type="text"
        class="mt-1 block w-full"
        v-model="form.location"
        required
      />
      <InputError class="mt-2" :message="form.errors.location" />
    </div>

    <div class="flex items-center justify-end mt-4">
      <PrimaryButton class="ml-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
        Ajouter l'expérience
      </PrimaryButton>
    </div>
  </form>
</template>

<script setup>
import { useForm } from '@inertiajs/vue3'
import { ref } from 'vue'
import axios from 'axios'
import InputError from '@/Components/InputError.vue'
import InputLabel from '@/Components/InputLabel.vue'
import PrimaryButton from '@/Components/PrimaryButton.vue'
import TextInput from '@/Components/TextInput.vue'

const isLoading = ref(false)
const error = ref('')

const form = useForm({
  title: '',
  company: '',
  location: '',
  start_date: '',
  end_date: '',
  description: '',
})

const handleCorrection = async () => {
  if (!form.description.trim()) return

  isLoading.value = true
  error.value = ''

  try {
    const response = await axios.post(route('experience.correct-description'), {
      description: form.description
    })

    if (response.data.success) {
      form.description = response.data.description
    } else {
      error.value = response.data.message || 'Une erreur est survenue lors de la correction'
    }
  } catch (err) {
    error.value = err.response?.data?.message || 'Une erreur est survenue lors de la correction'
    console.error('Erreur lors de la correction:', err)
  } finally {
    isLoading.value = false
  }
}

const submit = () => {
  form.post(route('experience.store'), {
    onSuccess: () => {
      form.reset()
    },
  })
}
</script>
